/**
 * generate-earth-shore-data.ts
 *
 * Builds src/common/view/EarthShoreDataHigh.ts from Natural Earth land polygons.
 * Source GeoJSON lives in data/natural-earth/ (110m by default; pass "50m" for finer detail).
 *
 * Run with: npm run earth-shore
 *           npm run earth-shore -- 50m
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type LonLat = [number, number];
type GeoJsonPolygon = LonLat[][];
type GeoJsonGeometry =
  | { type: "Polygon"; coordinates: GeoJsonPolygon }
  | { type: "MultiPolygon"; coordinates: GeoJsonPolygon[] };
type GeoJsonFeature = { geometry: GeoJsonGeometry };
type GeoJsonFeatureCollection = { features: GeoJsonFeature[] };

type EarthShorePoint = { x: number; y: number; z: number };

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const resolution = process.argv[2] === "50m" ? "50m" : "110m";
const inputPath = resolve(root, "data", "natural-earth", `ne_${resolution}_land.geojson`);
const outputPath = resolve(root, "src", "common", "view", "EarthShoreDataHigh.ts");

const DECIMALS = 4;

const lonLatToUnitSphere = (lon: number, lat: number): EarthShorePoint => {
  const latRad = (lat * Math.PI) / 180;
  const lonRad = (lon * Math.PI) / 180;
  const cosLat = Math.cos(latRad);
  return {
    x: Number((cosLat * Math.cos(lonRad)).toFixed(DECIMALS)),
    y: Number((cosLat * Math.sin(lonRad)).toFixed(DECIMALS)),
    z: Number(Math.sin(latRad).toFixed(DECIMALS)),
  };
};

const exteriorRingsFromGeometry = (geometry: GeoJsonGeometry): LonLat[][] => {
  if (geometry.type === "Polygon") {
    const ring = geometry.coordinates[0];
    return ring ? [ring] : [];
  }
  return geometry.coordinates.map((polygon) => polygon[0]).filter((ring): ring is LonLat[] => ring !== undefined);
};

const stripClosingDuplicate = (ring: LonLat[]): LonLat[] => {
  if (ring.length < 2) {
    return ring;
  }
  const first = ring[0];
  const last = ring[ring.length - 1];
  if (first && last && first[0] === last[0] && first[1] === last[1]) {
    return ring.slice(0, -1);
  }
  return ring;
};

const geojson = JSON.parse(readFileSync(inputPath, "utf8")) as GeoJsonFeatureCollection;

const polygons: EarthShorePoint[][] = [];
for (const feature of geojson.features) {
  for (const ring of exteriorRingsFromGeometry(feature.geometry)) {
    const openRing = stripClosingDuplicate(ring);
    if (openRing.length < 3) {
      continue;
    }
    polygons.push(openRing.map(([lon, lat]) => lonLatToUnitSphere(lon, lat)));
  }
}

const pointCount = polygons.reduce((sum, polygon) => sum + polygon.length, 0);

const formatPoint = (point: EarthShorePoint): string => `    { x: ${point.x}, y: ${point.y}, z: ${point.z} },`;

const polygonBlocks = polygons.map((polygon) => `  [\n${polygon.map(formatPoint).join("\n")}\n  ],`).join("\n");

const output = `/**
 * EarthShoreDataHigh.ts
 *
 * Closed land polygons on the unit sphere from Natural Earth ${resolution} land
 * (generated by scripts/generate-earth-shore-data.ts). Coordinates use +Z for
 * the north pole and the +X axis for the prime meridian, so longitude is
 * \`atan2(y, x)\`.
 *
 * @generated — do not edit by hand; run \`npm run earth-shore\` to regenerate.
 */

export type EarthShorePoint = { x: number; y: number; z: number };

export const EARTH_SHORE_POLYGONS_HIGH: readonly (readonly EarthShorePoint[])[] = [
${polygonBlocks}
];
`;

writeFileSync(outputPath, output);

console.log(`Wrote ${outputPath}`);
console.log(`  resolution: Natural Earth ${resolution}`);
console.log(`  polygons:   ${polygons.length}`);
console.log(`  points:     ${pointCount}`);
